#!/usr/bin/env bash
set -euo pipefail

if (( $# > 0 )); then
    exec /opt/Obsidian/obsidian "$@"
fi

if qdbus6 \
    org.kde.kglobalaccel \
    /component/kwin \
    org.kde.kglobalaccel.Component.invokeShortcut \
    dot-obsidian >/dev/null 2>&1; then
    exit 0
fi

exec /opt/Obsidian/obsidian
